# Generated by Django 4.2.6 on 2023-11-08 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_name_alter_article_img_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
